### ISSUE TITLE
Named exports and imports circulars

### ISSUE THREAD

**Issue by ml-devninja** [aackerman/circular-dependency-plugin#59]
Should this be considered as circular dependency?

file `a.ts`
```
import { anotherUtil } from "b.ts"

export const util = () => true

export const otherUtil = () => false

export const extraUtil = () => anotherUtil()
```

file `b.ts`

```
import { util } from "a.ts"

const function = () => util()

export const anotherUtil = () => true
```

only the exported named exports are attached to the code with tree shaking enabled, not whole file right?

**Comment by aackerman** [comment]
In this case the code would work, but the plugin isn't sophisticated enough to determine whether a dependency is immediately used, which would be an issue or is used later which isn't an issue. 

I'm going to close this because at this point the plugin only considers full file dependencies and not specific exports and I don't have intentions to support that functionality.
